name: "CRYPTOMANIA BACKEND"

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - closed

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd /var/www/html
            git stash
            git pull
            composer i
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            cd /var/www/html/@web
            npm run build
